---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
SiteConfig:
 Title: 'daniek::ch'
 
SSViewer:
  theme: 'corlate'
  
Director:
 environment_type: 'live'

Page:
  extensions:
    - WidgetPageExtension
    
  googleAnalytics:
    enabled: 'true'
    accountId: 'UA-31886076-1'