---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'corlate'
  
Director:
 environment_type: 'dev'

Page:
  extensions:
    - WidgetPageExtension
    
  googleAnalytics:
    enabled: 'true'
    accountId: 'UA-31886076-1'